In [1]:
import torch
import numpy as np
a = torch.FloatTensor(3, 2)
a

tensor([[1.0010e-38, 9.0918e-39],
        [1.0102e-38, 1.0194e-38],
        [2.9389e-39, 9.6429e-39]])

In [2]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [3]:
torch.FloatTensor([[1,2,3],[3,2,1]])

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [4]:
n = np.zeros(shape=(3, 2))
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
b = torch.tensor(n)
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [6]:
n = np.zeros(shape=(3, 2), dtype=np.float32)
torch.tensor(n)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [7]:
n = np.zeros(shape=(3,2))
torch.tensor(n, dtype=torch.float32)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [9]:
s = a.sum()
s

tensor(6)

In [11]:
s.item()

6

In [12]:
torch.tensor(1)

tensor(1)

In [13]:
a = torch.FloatTensor([2,3])
a

tensor([2., 3.])

In [14]:
# ca = a.to('cuda'); ca
# AssertionError: Torch not compiled with CUDA enabled

AssertionError: Torch not compiled with CUDA enabled

In [16]:
print(a + 1)
# print(ca + 1)
# print(ca.device)

tensor([3., 4.])


In [17]:
v1 = torch.tensor([1.0, 1.0], =True)
v2 = torch.tensor([2.0, 2.0])

In [18]:
v_sum = v1 + v2
v_res = (v_sum*2).sum()
v_res

tensor(12., grad_fn=<SumBackward0>)

In [20]:
print(v1.is_leaf, v2.is_leaf)
print(v_sum.is_leaf, v_res.is_leaf)
print(v1.requires_grad)

True True
False False
True


In [21]:
print(v2.requires_grad)
print(v_sum.requires_grad)
print(v_res.requires_grad)
print(v_res.backward())
print(v1.grad)

False
True
True
None
tensor([2., 2.])


In [23]:
print(v2.grad)

None


In [24]:
import torch.nn as nn
l = nn.Linear(2, 5)
v = torch.FloatTensor([1, 2])
l(v)

tensor([ 0.1638,  0.7242,  0.2752, -1.0054, -1.9231], grad_fn=<AddBackward0>)

In [25]:
s = nn.Sequential(
nn.Linear(2, 5),
nn.ReLU(),
nn.Linear(5, 20),
nn.ReLU(),
nn.Linear(20, 10),
nn.Dropout(p=0.3),
nn.Softmax(dim=1))
s

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): Dropout(p=0.3, inplace=False)
  (6): Softmax(dim=1)
)

In [ ]:
from ignite.engine import Engine, Events

def training(engine, batch):
    optimizer.zero_grad()
    x, y = prepare_batch()
    y_out = model(x)
    loss = loss_fn(y_out, y)
    loss.backward()
    optimizer.step()
    return loss.item()

engine = Engine(training)
engine.run(data)

# This code is not runnable, as it misses lots of stuff, like the data source, model,
# and optimizer creation, but it shows the basic idea of Ignite usage.